name: frocc
channels:
- astropy
- conda-forge
- defaults
- pkgw-forge
dependencies:
- python=3.6
- pip
- numpy
- scipy
- matplotlib
- casa-tools
- seaborn
- click
- pandas
- jinja2
- pip:
  - casatasks
  - -rrequirements.txt